In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((20,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.random.rand(3,3)

array([[0.61674701, 0.22533929, 0.50719997],
       [0.17362367, 0.67784103, 0.28989443],
       [0.24922422, 0.65802471, 0.86961252]])

In [27]:
np.random.randn(3,3)

array([[ 0.6421227 , -0.82495776,  0.68959169],
       [-1.09675732, -0.8559507 , -1.80833147],
       [ 0.52753815,  1.24118486,  2.25284597]])

In [30]:
np.random.randint(1,1000,5)

array([802, 766, 899, 143, 939])

In [31]:
arr = np.arange(25)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [42]:
ranarr = np.random.randint(0,50,10)

In [43]:
ranarr

array([48, 36,  1, 27, 46,  5, 38, 41, 25,  1])

In [35]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
ranarr

array([ 2, 31, 45, 24,  7,  3, 49, 37, 36, 44])

In [38]:
ranarr.max()
#ranarr.min()

49

In [39]:
ranarr.min()

2

In [44]:
ranarr.argmax()

0

In [45]:
arr.dtype

dtype('int64')

In [46]:
from numpy.random import randint

In [47]:
randint(2,10)

4